booking_save:
    path: /booking
    controller: App\Controller\BookingController::saveBooking
    methods:   [POST]
booking_last:
    path: /bookings/last
    controller: App\Controller\BookingController::lastBooking
    methods:   [GET]    
booking_all:
    path: /bookings/all
    controller: App\Controller\BookingController::allBookings
    methods:   [GET] 
       