movie_cinema:
    path: /movies/{cinemaUrl}/byCinema
    controller: App\Controller\MovieController::byCinema
movie_movie:
    path: /movies/{movieId}/byMovie
    controller: App\Controller\MovieController::byMovie        