App\Entity\Movies:
    type: entity
    #repositoryClass: App\Repository\MoviesRepository  
    table: movies
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
        director:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        screenshot:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        synopsis:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    lifecycleCallbacks: {  }
