App\Entity\SeatState:
    type: entity
    #repositoryClass: App\Repository\SeatStateRepository  
    table: seat_state
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
    lifecycleCallbacks: {  }
