App\Entity\Customers:
    type: entity
    #repositoryClass: App\Repository\CustomersRepository  
    table: customers
    indexes:
        user:
            columns:
                - user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        phone:
            type: string
            nullable: true
            length: 14
            options:
                fixed: false
        creditCard:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: credit_card
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
